# Generated by Django 4.1.1 on 2022-09-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia1',
            name='primerparcial',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='materia2',
            name='primerparcial',
            field=models.CharField(max_length=20),
        ),
    ]
